### ISSUE TITLE
Can't build due to an export error on the module

### ISSUE THREAD

**Issue by vabadio** [lukeed/escalade#9]
Hi there,

I built a small app on Astro with Svelte and I'm now getting this error when trying to generate the build:

```
'promisify' is not exported by __vite-browser-external, imported by node_modules/escalade/dist/index.mjs
file: /Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/escalade/dist/index.mjs:3:9
1: import { dirname, resolve } from 'path';
2: import { readdir, stat } from 'fs';
3: import { promisify } from 'util';
            ^
4: 
5: const toStats = promisify(stat);
 error   'promisify' is not exported by __vite-browser-external, imported by node_modules/escalade/dist/index.mjs
  File:
    /Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/escalade/dist/index.mjs:3:9
  Code:
    1: import { dirname, resolve } from 'path';
    2: import { readdir, stat } from 'fs';
    3: import { promisify } from 'util';
                ^
    4: 
    5: const toStats = promisify(stat);
  Stacktrace:
Error: 'promisify' is not exported by __vite-browser-external, imported by node_modules/escalade/dist/index.mjs
    at error (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at Identifier.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at CallExpression.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at VariableDeclarator.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at VariableDeclaration.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at Program.bind (file:///Users/victor/Work/Camino/astro-playground/camino-astro/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
```

**Comment by lukeed** [comment]
`util` is a native NodeJS module & the `promisfy` export has been there since Node 8.x

It sounds like you're accidentally including `escalade` in your browser bundle, somehow. Are you bundling in the browser?
Either way, the true cause of the error is that the `__vite-browser-external` shim bundle does not include a `util.promisfy` polyfill, but it's _appearing_ because you're trying to include a NodeJS module (escalade) into a browser output.

**Comment by unaghii** [comment]
@lukeed I understand, however I'm not actively using this lib. I think the svelte module is calling it.

**Comment by lukeed** [comment]
this would surface all throughout the svelte ecosystem if this were the case. I'm fairly confident it's something specific to your build. I suggest stripping away everything in your project & adding it back until the problem reappears.

Closing this as it's not an issue with escalade
